#!/usr/bin/env bash
# A demonstration app for Snapcraft Template Plus, essentially only show a friendly message
# 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com> © 2019

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

if [ -v 'BASH_SOURCE[0]' ]; then
    RUNTIME_EXECUTABLE_PATH="$(realpath --strip "${BASH_SOURCE[0]}")"
    RUNTIME_EXECUTABLE_FILENAME="$(basename "${RUNTIME_EXECUTABLE_PATH}")"
    RUNTIME_EXECUTABLE_NAME="${RUNTIME_EXECUTABLE_FILENAME%.*}"
    RUNTIME_EXECUTABLE_DIRECTORY="$(dirname "${RUNTIME_EXECUTABLE_PATH}")"
    RUNTIME_COMMANDLINE_BASECOMMAND="${0}"
    # We intentionally leaves these variables for script developers
    # shellcheck disable=SC2034
    declare -r \
        RUNTIME_EXECUTABLE_PATH \
        RUNTIME_EXECUTABLE_FILENAME \
        RUNTIME_EXECUTABLE_NAME \
        RUNTIME_EXECUTABLE_DIRECTORY \
        RUNTIME_COMMANDLINE_BASECOMMAND
fi
declare -ar RUNTIME_COMMANDLINE_ARGUMENTS=("${@}")

init(){
    local icon

    # HACK: Allow testing the script in-place
    if ! test -v SNAP; then
        icon="${RUNTIME_EXECUTABLE_DIRECTORY}"/snap/gui/my-awesome-app.png
    else
        icon="${SNAP}"/meta/gui/my-awesome-app.png
    fi

    zenity \
        --info \
        --ok-label='Got it!' \
        --title='My Awesome App.' \
        --text='This is a demonstrative application for Snapcrafters Template Plus.\nIt indicates that the snapped application has been launched properly.' \
        --window-icon="${icon}" \
        --width=600
    exit $?
}

# WORKAROUND: `@` expansion triggeres unbound variable error in Bash 4.3(Ubuntu 16.04)
# http://mywiki.wooledge.org/BashFAQ/112#Negatives
if test "${#RUNTIME_COMMANDLINE_ARGUMENTS[@]}" -ne 0; then
    init "${RUNTIME_COMMANDLINE_ARGUMENTS[@]}"
else
    init
fi
