# Copyright 2021 Dani Llewellyn <https://github.com/diddledani>
# SPDX-License-Identifier: CC-BY-SA-4.0
name: 🧪 Test snap can be built on x86_64

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snapcore/action-build@v1
        id: build

      - uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: 'false'
          # Plugs and Slots declarations to override default denial (requires store assertion to publish)
          # plugs: ./plug-declaration.json
          # slots: ./slot-declaration.json

      - name: Send CI result notification to the Telegram channel
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: '@brlin_project_ci_results'
          token: ${{ secrets.telegram_bot_api_token_ci }}
          status: ${{ job.status }}
